-- H2 2.3.232; 
;              
CREATE USER IF NOT EXISTS "" SALT '' HASH '' ADMIN;            
CREATE CACHED TABLE "PUBLIC"."KINGDOMS_GLOBALS"(
    "ID" BOOLEAN NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "LASTSTART" BIGINT NOT NULL,
    "LASTDISABLE" BIGINT NOT NULL,
    "LASTSTATE" CHARACTER VARYING(30) NOT NULL,
    "LASTSERVERVERSION" CHARACTER VARYING(30) NOT NULL,
    "LASTKINGDOMSVERSION" CHARACTER VARYING(30) NOT NULL,
    "INSTALLEDADDONS" JSON,
    "STOCKS" JSON,
    "FLAGS" JSON,
    "STATISTICS" JSON,
    "LOGS" JSON,
    "METADATA" JSON
);              
ALTER TABLE "PUBLIC"."KINGDOMS_GLOBALS" ADD CONSTRAINT "PUBLIC"."KINGDOMS_GLOBALS_PKEY" PRIMARY KEY("ID");     
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.KINGDOMS_GLOBALS;         
INSERT INTO "PUBLIC"."KINGDOMS_GLOBALS" VALUES
(TRUE, 1, 1758325141295, 0, 'ENABLED', '1.21.8', '1.17.20-BETA', JSON '{}', JSON '{}', NULL, NULL, NULL, NULL); 
CREATE CACHED TABLE "PUBLIC"."KINGDOMS_PLAYERS"(
    "ID" UUID NOT NULL,
    "LANG" CHARACTER(2) NOT NULL,
    "KINGDOM" UUID,
    "RANK" CHARACTER VARYING(50),
    "NATIONALRANK" CHARACTER VARYING(50),
    "JOINEDAT" BIGINT,
    "LASTPOWERCHECKUP" BIGINT,
    "LASTDONATIONTIME" BIGINT,
    "LASTDONATIONAMOUNT" DOUBLE PRECISION,
    "TOTALDONATIONS" DOUBLE PRECISION,
    "MARKERSTYPE" CHARACTER VARYING(50),
    "CHATCHANNEL" CHARACTER VARYING(50),
    "POWER" DOUBLE PRECISION,
    "MAPSIZE_HEIGHT" INTEGER,
    "MAPSIZE_WIDTH" INTEGER,
    "READMAILS" JSON,
    "CLAIMS" JSON,
    "PROTECTEDBLOCKS" JSON,
    "MUTEDCHANNELS" JSON,
    "INVITES" JSON,
    "JAILCELL_WORLD" CHARACTER VARYING(64),
    "JAILCELL_X" INTEGER,
    "JAILCELL_Z" INTEGER,
    "FLAGS" JSON,
    "STATISTICS" JSON,
    "LOGS" JSON,
    "METADATA" JSON
);               
ALTER TABLE "PUBLIC"."KINGDOMS_PLAYERS" ADD CONSTRAINT "PUBLIC"."KINGDOMS_PLAYERS_PKEY" PRIMARY KEY("ID");     
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.KINGDOMS_PLAYERS;         
INSERT INTO "PUBLIC"."KINGDOMS_PLAYERS" VALUES
(UUID '024fdfad-d078-3149-8896-20d579490a75', 'EN', UUID 'a9d39e78-de28-4430-b327-5ef6642a64b4', 'king', NULL, 1758148848845, NULL, 1758059755769, 0.0, 0.0, NULL, 'GLOBAL', NULL, NULL, NULL, JSON '[]', JSON '["world, -509, -257"]', NULL, JSON '[]', JSON '{}', NULL, NULL, NULL, JSON '{"ADMIN":false}', JSON '{"KINGDOMS_CREATED":{"type":"NUMBER","value":9}}', JSON '[]', JSON '{}');   
CREATE CACHED TABLE "PUBLIC"."KINGDOMS_LANDS"(
    "ID_WORLD" CHARACTER VARYING(64) NOT NULL,
    "ID_X" INTEGER NOT NULL,
    "ID_Z" INTEGER NOT NULL,
    "KINGDOM" UUID,
    "CLAIMEDBY" UUID,
    "STRUCTURES" JSON,
    "TURRETS" JSON,
    "PROTECTEDBLOCKS" JSON,
    "SINCE" BIGINT NOT NULL,
    "STATISTICS" JSON,
    "LOGS" JSON,
    "METADATA" JSON
);           
ALTER TABLE "PUBLIC"."KINGDOMS_LANDS" ADD CONSTRAINT "PUBLIC"."KINGDOMS_LANDS_PKEY" PRIMARY KEY("ID_WORLD", "ID_X", "ID_Z");   
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.KINGDOMS_LANDS;           
INSERT INTO "PUBLIC"."KINGDOMS_LANDS" VALUES
('world', 161, -472, NULL, NULL, JSON '{"2584, 129, -7546":{"type":"powercell","level":2,"building":{"architect":"WORLD_EDIT_FINISHED","facing":"SOUTH","schematic":"structures/powercell/2"},"name":"Powercell"}}', JSON '{}', JSON '{}', 1758063448907, JSON '{}', JSON '[]', JSON '{}'),
('world', 160, -473, NULL, NULL, JSON '{}', JSON '{"2568, 131, -7554":{"type":"flame","level":3,"building":{"architect":"WORLD_EDIT_FINISHED","facing":"WEST","schematic":"turrets/flame/3"},"ammo":4565}}', JSON '{}', 1758063448907, JSON '{}', JSON '[]', JSON '{}'),
('world', -509, -257, UUID 'a9d39e78-de28-4430-b327-5ef6642a64b4', UUID '024fdfad-d078-3149-8896-20d579490a75', JSON '{"-8140, 69, -4106":{"type":"nexus","level":1,"building":{"architect":"SINGLE_BLOCKED_FINISHED","facing":"SOUTH"},"name":"Nexus"}}', JSON '{}', JSON '{}', 1758148848848, JSON '{}', JSON '[]', JSON '{}');            
CREATE CACHED TABLE "PUBLIC"."KINGDOMS_KINGDOMS"(
    "ID" UUID NOT NULL,
    "NAME" CHARACTER VARYING(100) NOT NULL,
    "LEVEL" INTEGER NOT NULL,
    "TAG" CHARACTER VARYING(50),
    "RESOURCEPOINTS" DOUBLE PRECISION NOT NULL,
    "BANK" DOUBLE PRECISION NOT NULL,
    "TAXES" JSON,
    "SHIELDSINCE" BIGINT NOT NULL,
    "SHIELDTIME" BIGINT NOT NULL,
    "SINCE" BIGINT NOT NULL,
    "COLORS" JSON,
    "FLAG" JSON,
    "BANNER" JSON,
    "NEXUS_WORLD" CHARACTER VARYING(64),
    "NEXUS_X" INTEGER,
    "NEXUS_Y" INTEGER,
    "NEXUS_Z" INTEGER,
    "HOME_WORLD" CHARACTER VARYING(64),
    "HOME_X" DOUBLE PRECISION,
    "HOME_Y" DOUBLE PRECISION,
    "HOME_Z" DOUBLE PRECISION,
    "HOME_YAW" REAL,
    "HOME_PITCH" REAL,
    "RANKS" JSON,
    "RELATIONSHIPREQUESTS" JSON,
    "RELATIONS" JSON,
    "ATTRIBUTES" JSON,
    "FLAGS" JSON,
    "KING" UUID,
    "NATION" UUID,
    "LORE" CHARACTER VARYING(300),
    "CHAMPIONTYPE" CHARACTER VARYING(50),
    "MAXLANDSMODIFIER" BIGINT,
    "LASTINVASION" BIGINT,
    "MEMBERS" JSON NOT NULL,
    "LANDS" JSON,
    "UPGRADES_MISC" JSON,
    "UPGRADES_POWERUPS" JSON,
    "UPGRADES_CHAMPIONS" JSON,
    "NEXUSCHEST" JSON,
    "BOOK" JSON,
    "MAILS" JSON,
    "CHALLENGES" JSON,
    "INVITECODES" JSON,
    "STATISTICS" JSON,
    "LOGS" JSON,
    "METADATA" JSON
);
ALTER TABLE "PUBLIC"."KINGDOMS_KINGDOMS" ADD CONSTRAINT "PUBLIC"."KINGDOMS_KINGDOMS_PKEY" PRIMARY KEY("ID");   
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.KINGDOMS_KINGDOMS;        
INSERT INTO "PUBLIC"."KINGDOMS_KINGDOMS" VALUES
(UUID 'a9d39e78-de28-4430-b327-5ef6642a64b4', 'GAME', 1, NULL, 0.0, 0.0, JSON '{}', 0, 0, 1758148848844, JSON '{}', NULL, NULL, 'world', -8140, 69, -4106, 'world', -8139.7, 70.0, -4105.5, -176.7, 84.7, JSON '{"general":{"name":"General","color":"{$s}","symbol":"\u2747","priority":1,"maxClaims":-1,"material":"DIAMOND_BLOCK","permissions":["BROADCAST","BUILD","NEXUS_BUILD","CLAIM","UNCLAIM","MANAGE_RANKS","WITHDRAW","INTERACT","USE","HOME","SET_HOME","INVADE","INVITE","KICK","LORE","NEXUS","FLY","NATION","TRUCE","ENEMY","ALLIANCE","NEXUS_CHEST","OUTPOST","UPGRADE","INSTANT_TELEPORT","READ_MAILS","MANAGE_MAILS","STRUCTURES","TURRETS","VIEW_LOGS"]},"king":{"name":"King","color":"&c","symbol":"\u265a","priority":0,"maxClaims":-1,"material":"EMERALD_BLOCK"},"knight":{"name":"Knight","color":"&e","symbol":"\u265c","priority":2,"maxClaims":10,"material":"GOLD_BLOCK","permissions":["BUILD","NEXUS_BUILD","CLAIM","UNCLAIM_OWNED","WITHDRAW","INTERACT","USE","HOME","INVADE","INVITE","NEXUS","FLY","NEXUS_CHEST","INSTANT_TELEPORT","INVSEE","READ_MAILS","TURRETS"]},"member":{"name":"Member","color":"{$p}","symbol":"\u265f","priority":3,"maxClaims":0,"material":"IRON_BLOCK","permissions":["BUILD","INTERACT","USE","HOME","INVADE","NEXUS","READ_MAILS"]}}', JSON '{}', JSON '{}', JSON '{"ALLY":["CEASEFIRE","INTERACT","HOME","FLY","SHOW_HOLOGRAMS","TURRET_CEASEFIRE","MANAGE_TURRETS","MANAGE_STRUCTURES"],"ENEMY":["FLY","INVADE"],"NEUTRAL":["INVADE"],"NATION":["BUILD","CEASEFIRE","INTERACT","HOME","USE","SHOW_HOLOGRAMS","TURRET_CEASEFIRE","MANAGE_TURRETS","MANAGE_STRUCTURES"],"TRUCE":["CEASEFIRE","FLY","TURRET_CEASEFIRE"]}', JSON '{"PACIFIST":false}', UUID '024fdfad-d078-3149-8896-20d579490a75', NULL, NULL, NULL, 0, 0, JSON '["024fdfad-d078-3149-8896-20d579490a75"]', JSON '["world, -509, -257"]', JSON '{}', JSON '{}', JSON '{}', JSON '{}', JSON '{}', JSON '[]', JSON '{}', JSON '{}', JSON '{"LANDS":{"type":"GROUP","value":{"TOTAL":{"type":"NUMBER","value":1}}},"MEMBERS":{"type":"GROUP","value":{"TOTAL_DEATHS":{"type":"NUMBER","value":1},"TOTAL":{"type":"NUMBER","value":1}}}}', JSON '[{"namespace":"KINGDOM_JOIN","time":1758148848845,"player":"024fdfad-d078-3149-8896-20d579490a75"},{"namespace":"KINGDOM_CLAIM","time":1758148848847,"player":"024fdfad-d078-3149-8896-20d579490a75","lands":["world, -509, -257"]},{"namespace":"STRUCTURES_NEXUS_MOVE","time":1758148848848,"player":"024fdfad-d078-3149-8896-20d579490a75","to":"world, -8140, 69, -4106"},{"namespace":"KINGDOM_PACIFISM_CHANGE","time":1758148851303,"player":"024fdfad-d078-3149-8896-20d579490a75"}]', JSON '{}');       
CREATE CACHED TABLE "PUBLIC"."KINGDOMS_NATIONS"(
    "ID" UUID NOT NULL,
    "NAME" CHARACTER VARYING(100) NOT NULL,
    "LEVEL" INTEGER NOT NULL,
    "TAG" CHARACTER VARYING(50),
    "RESOURCEPOINTS" DOUBLE PRECISION NOT NULL,
    "BANK" DOUBLE PRECISION NOT NULL,
    "TAXES" JSON,
    "SHIELDSINCE" BIGINT NOT NULL,
    "SHIELDTIME" BIGINT NOT NULL,
    "SINCE" BIGINT NOT NULL,
    "COLORS" JSON,
    "FLAG" JSON,
    "BANNER" JSON,
    "NEXUS_WORLD" CHARACTER VARYING(64),
    "NEXUS_X" INTEGER,
    "NEXUS_Y" INTEGER,
    "NEXUS_Z" INTEGER,
    "HOME_WORLD" CHARACTER VARYING(64),
    "HOME_X" DOUBLE PRECISION,
    "HOME_Y" DOUBLE PRECISION,
    "HOME_Z" DOUBLE PRECISION,
    "HOME_YAW" REAL,
    "HOME_PITCH" REAL,
    "RANKS" JSON,
    "RELATIONSHIPREQUESTS" JSON,
    "RELATIONS" JSON,
    "ATTRIBUTES" JSON,
    "FLAGS" JSON,
    "CAPITAL" UUID NOT NULL,
    "KINGDOMS" JSON NOT NULL,
    "STATISTICS" JSON,
    "LOGS" JSON,
    "METADATA" JSON
);
ALTER TABLE "PUBLIC"."KINGDOMS_NATIONS" ADD CONSTRAINT "PUBLIC"."KINGDOMS_NATIONS_PKEY" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.KINGDOMS_NATIONS;         
CREATE CACHED TABLE "PUBLIC"."KINGDOMS_MAILS"(
    "ID" UUID NOT NULL,
    "FROMGROUP" UUID NOT NULL,
    "SENDER" UUID NOT NULL,
    "INREPLYTO" UUID,
    "SENT" BIGINT NOT NULL,
    "SUBJECT" CHARACTER VARYING(300) NOT NULL,
    "RECIPIENTS" JSON NOT NULL,
    "MESSAGE" JSON NOT NULL,
    "STATISTICS" JSON,
    "LOGS" JSON,
    "METADATA" JSON
); 
ALTER TABLE "PUBLIC"."KINGDOMS_MAILS" ADD CONSTRAINT "PUBLIC"."KINGDOMS_MAILS_PKEY" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.KINGDOMS_MAILS;           
